resolver: lts-8.0

packages:
- '.'

extra-deps: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# extra directories for C libs, if not in a standard place
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
